kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foghorn
subjects:
- kind: ServiceAccount
  name: foghorn
roleRef:
  kind: Role
  name: foghorn
  apiGroup: rbac.authorization.k8s.io
